version: '3.8'
services:
  odoo:
    image: "mlgmag/odoo-docker:latest"
    volumes:
      - ./docker/odoo.conf:/etc/odoo/odoo.conf
      - ./logs/:/opt/odoo/log/
      - ./data_dir/:/opt/odoo/data_dir/
    networks:
      - odoo-network
    ports:
      - "8069:8069"
      - "8071:8071"
      - "8072:8072"

  odoo-db:
    image: "postgres:15-alpine"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: odoo1234
    volumes:
      - ./database_data:/var/lib/postgresql/data
    networks:
      - odoo-network
    ports:
      - "5432:5432"

networks:
  odoo-network:
    driver: bridge

